### ISSUE TITLE
Cannot click participants on touch device

### ISSUE THREAD

**Issue by bingvanmoorsel** [flagrow/byobu#23]
First of all id like to say thank you for this great plugin.

a bug i ran into is that im not able to select a participant on my ipad. :-(
It blinks but doesn't select the user.

Kind regards,
Bing

**Comment by Luceos** [comment]
Easy solution: don't use an ipad ;)

Any idea where this goes wrong, you mention selecting a user, so this occurs on the dropdown on the search?

**Comment by bingvanmoorsel** [comment]
https://github.com/flagrow/byobu/blob/master/js/forum/dist/extension.js#L817

I think that is where the event is not correctly catched on a touch device?

**Comment by Luceos** [comment]
Could you try setting the dependency to `dev-master`. It seems the event touch should suffice here.

**Comment by Luceos** [comment]
beta.13 tagged

**Comment by bingvanmoorsel** [comment]
Goodmorning Loceos,

Sorry for the late reply, the issues seems to presists. i've tried using dev-master but it doesnt seem to work.

Greetings.
Bing

**Comment by issyrocks12** [comment]
Can confirm that the issue still persists, I'll see if I can figure something out

**Comment by Luceos** [comment]
Perhaps adding jquery-mobile events might solve this issue. I'm not sure what else might be a solution in this situation.

**Comment by bingvanmoorsel** [comment]
Did you manage to find the problem yet? would really help me out :-)

**Comment by Luceos** [comment]
@bingvanmoorsel haven't had the time yet my apologies. If you would be able to provide a solution I'll gladly merge ❤️

**Comment by issyrocks12** [comment]
I'll take a crack at it as soon as I finish up the extension I'm currently
working on

**Comment by issyrocks12** [comment]
I'll take a crack at it in the upcoming days

**Comment by issyrocks12** [comment]
Looks like a CSS issue, pull request coming soon

**Comment by issyrocks12** [comment]
Fixed in #29

**Comment by Luceos** [comment]
@bingvanmoorsel going to tag it, can you test it afterwards please 😇

**Comment by bingvanmoorsel** [comment]
@Luceos Will do! i will get back to you.

**Comment by bingvanmoorsel** [comment]
@Luceos  and @issyrocks12 sadly the styling trick didnt fix the bug. the participant is clickable and gets highlighted but it doesnt get added tot the list. :(

**Comment by issyrocks12** [comment]
Did you clear your Flarum and browser cache?

**Comment by issyrocks12** [comment]
Take two: #30

**Comment by bingvanmoorsel** [comment]
@issyrocks12  Thanks a million! @Luceos it works now. i used dev-master now. if you could tag this build it would be great! thanks allot both!

**Comment by Luceos** [comment]
Will tag within a few minutes. @issyrocks12 thanks for your efforts, greatly appreciated!
